# Generated by Django 5.2 on 2025-05-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(max_length=20, verbose_name="Номер заказа"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Принят"),
                            ("in_progress", "В работе"),
                            ("documents", "Документы"),
                            ("suspended", "Приостановлен"),
                            ("reschedule", "Перенос"),
                            ("ready", "Готово"),
                        ],
                        default="accepted",
                        verbose_name="Статус заказа",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="Изменен"),
                ),
                (
                    "month",
                    models.CharField(blank=True, max_length=10, verbose_name="Месяц"),
                ),
                ("week", models.IntegerField(blank=True, verbose_name="Неделя")),
                (
                    "manager",
                    models.CharField(
                        max_length=20,
                        verbose_name="Менеджер. Создать отдельную модель в приложении Пользователей",
                    ),
                ),
                (
                    "customer",
                    models.CharField(
                        max_length=20,
                        verbose_name="Заказчик. Создать отдельную модель в приложении Пользователей",
                    ),
                ),
                (
                    "technologist",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Технолог. Создать отдельную модель в приложении Пользователей",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, verbose_name="Масса"
                    ),
                ),
                (
                    "package",
                    models.IntegerField(blank=True, verbose_name="Количество упаковок"),
                ),
                ("mdf", models.BooleanField(default=False, verbose_name="МДФ")),
                (
                    "furniture",
                    models.BooleanField(default=False, verbose_name="Фурнитура"),
                ),
                ("grass", models.BooleanField(default=False, verbose_name="Стекло")),
                ("cnc", models.BooleanField(default=False, verbose_name="ЧПУ")),
                (
                    "materials",
                    models.CharField(
                        blank=True, verbose_name="Материалы. Создать отдельную модель"
                    ),
                ),
                (
                    "quadrature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Квадратура",
                    ),
                ),
                (
                    "serial",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Серийная продукция",
                    ),
                ),
                (
                    "portal",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Каминные порталы",
                    ),
                ),
                (
                    "reclamation",
                    models.CharField(max_length=250, verbose_name="Причина рекламации"),
                ),
            ],
        ),
    ]
