# Generated by Django 5.2 on 2025-05-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Заказ", "verbose_name_plural": "Заказы"},
        ),
        migrations.AlterField(
            model_name="order",
            name="reclamation",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="Причина рекламации"
            ),
        ),
    ]
