# Generated by Django 5.2 on 2025-05-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_options_alter_order_reclamation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="package",
            field=models.IntegerField(
                blank=True, default=0, verbose_name="Количество упаковок"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="weight",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="Масса"
            ),
        ),
    ]
