# Generated by Django 5.2 on 2025-05-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_package_alter_order_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="month",
            field=models.IntegerField(max_length=10, null=True, verbose_name="Месяц"),
        ),
        migrations.AlterField(
            model_name="order",
            name="package",
            field=models.IntegerField(
                default=0, null=True, verbose_name="Количество упаковок"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="portal",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                null=True,
                verbose_name="Каминные порталы",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="quadrature",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                null=True,
                verbose_name="Квадратура",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="serial",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                null=True,
                verbose_name="Серийная продукция",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("accepted", "Принят"),
                    ("in_progress", "В работе"),
                    ("documents", "Документы"),
                    ("suspended", "Приостановлен"),
                    ("reschedule", "Перенос"),
                    ("ready", "Готово"),
                ],
                default="accepted",
                max_length=20,
                verbose_name="Статус заказа",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="week",
            field=models.IntegerField(null=True, verbose_name="Неделя"),
        ),
    ]
